name: Test

on:
  workflow_call:
    secrets:
      FIZZY_GH_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  test:
    name: Tests (PostgreSQL)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: fizzy_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_ADAPTER: postgres
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_TEST_DB: fizzy_test
      POSTGRES_TEST_CABLE_DB: fizzy_test_cable
      POSTGRES_TEST_QUEUE_DB: fizzy_test_queue
      POSTGRES_TEST_CACHE_DB: fizzy_test_cache

    steps:
      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libpq-dev libvips curl ffmpeg chromium-browser

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        run: bin/rails db:setup test

      - name: Run system tests
        env:
          CHROME_BIN: /usr/bin/chromium-browser
        run: PARALLEL_WORKERS=1 bin/rails test:system
